apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-project-deployment
  labels:
    app: docker-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-project
  template:
    metadata:
      labels:
        app: docker-project
    spec:
      containers:
        - name: docker-project
          image: docker-project:latest
          imagePullPolicy: IfNotPresent
